main: com.gmail.erikbigler.applessentials.Applessentials
name: Applessentials
version: 1.23
author: ebiggz
description: General purpose plugin for AppleCraft.
depend: [Herochat, PermissionsEx, Vault]
commands:
    playerinfo:
        description: Mod command for viewing player info.
        usage: /<command> [playername]
    pi:
        description: Mod command for viewing player info.
        usage: /<command> [playername]
    allchat:
        description: Mod command for seeing all chat.
        usage: /<command>
    isign:
        description: Mod command for interactive signs.
        usage: /<command>
    colors:
        description: See color codes.
        usage: /<command>
    applecraft:
        description: Access to some general commands.
        usage: /<command>
    com:
        description: Clickable staff command list.
        usage: /<command>
    staff:
        description: Clickable staff command list.
        usage: /<command>
    channels:
        description: Clickable channel command list.
        usage: /<command>
    resmax:
        description: Res max command.
        usage: /<command>
    restool:
        description: Res tool command.
        usage: /<command>
    slap:
        description: Res tool command.
        usage: /<command>
    map:
        description: Res tool command.
        usage: /<command>
    warn:
        description: Issues warnings to players.
        usage: /<command> [player] [reason]
    warninfo:
        description: Shows warn info.
        usage: /<command> [player]
    resetwarn:
        description: Resets warn data.
        usage: /<command> [player] [entries/points]
    setwarn:
        description: Sets warn data.
        usage: /<command> [player] [#ofpoints]
    unwarn:
        description: Undo a warn.
        usage: /<command> [player]
    serverinfo:
        description: See server information.
        usage: /<command>
    si:
        description: See server information.
        usage: /<command>
    tplastknown:
        description: Teleport to a players last known location.
        usage: /<command> [player]
    speedtest:
        description: Teleport to a players last known location.
        usage: /<command> [player]
    hideplayers:
        description: Hides players in spawn.
        usage: /<command>
    hidechat:
        description: Hides chat.
        usage: /<command>
    hidepm:
        description: Hides private messages.
        usage: /<command>
    hidepms:
        description: Hides private messages.
        usage: /<command>
    friends:
        description: Hides private messages.
        usage: /<command>
    settings:
        description: Hides private messages.
        usage: /<command>
permissions:
    applecraft.youtuber:
        default: false
    applecraft.warn:
        default: false
    applecraft.warninfo.others:
        default: false
    applecraft.setwarn:
        default: false
    applecraft.resetwarn:
        default: false
    applecraft.admin:
        default: false
    applecraft.owner:
        default: false
    applecraft.spawnmenudisable:
        default: false
    applecraft.mod:
        default: false
        children:
            applecraft.warn: true
            applecraft.warninfo.others: true
    applecraft.supermod:
        default: false
        children:
            applecraft.mod: true
            applecraft.setwarn: true
            applecraft.unwarn: true
            applecraft.resetwarn: true
            applecraft.spawnmenudisable: true
    applecraft.*:
        default: op
        children:
            applecraft.mod: true
            applecraft.supermod: true
            applecraft.admin: true
